server:
  port: 80

spring:
  application:
    name: zuul
zuul:
  routes:
    to163:
      path: /163/**
      url: http://www.163.com
    toDemo:
      path: /to/**
      url: forward:/zuul
    toIndex:
      path: /index/**
      serviceId: cloud-index
    cloud-user:
      path: /user/**

    cloud-index: /idx/**


